### ISSUE TITLE
Erro ao consultar CEP

### ISSUE THREAD

**Issue by costaalvesgabriel** [wrparra/Correios.NET#7]
Alguns dias atrás a biblioteca estava funcionando normalmente. Porém agora ocorre um erro ao Desserializar a resposta.

StackTrace
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadAndMoveToContent()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at Correios.NET.Services.<GetAddressesAsync>d__7.MoveNext()
   
   
O erro acontece na linha 55 da imagem
![image](https://user-images.githubusercontent.com/85899283/121939843-d4a40300-cd23-11eb-8553-da9f66fa93e6.png)

**Comment by wrparra** [comment]
Corrigido. 
Obrigado!

**Comment by costaalvesgabriel** [comment]
Funcionou corretamente. Muito Obrigado!
